apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../deployment/frontend-deployment.yaml
- ../deployment/service-frontend-lb.yaml
- ../issuers/letsencrypt-prod.yaml
- ../ingress/ingress_ssl.yaml

images:
- name: amitbb16/frontend-app
  newTag: 1.0.0