# Service targeting gitlab instances
apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    app: postgres
spec:
  ports:
  - name: metrics # expose metrics port
    port: 3306 # defined in gitlab chart
    targetPort: metrics
    protocol: TCP
  selector:
    app: postgres # target gitlab pods

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - image: postgres:11.22-bullseye
        name: postgres
        env:
          # Use secret in real usage
        - name: POSTGRES_ROOT_PASSWORD
          value: password
        ports:
        - containerPort: 3306
          name: postgres
        