apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: mysql-monitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: default
  labels:
    app: mysql
    release: prometheus
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: mysql-1
    app.kubernetes.io/name: mysql
    app.kubernetes.io/part-of: prometheus-operated
    app.kubernetes.io/version: 0.26.0
    app.kubernetes.io/managed-by: Helm
spec:
  selector:
    matchLabels:
      app: mysql
      release: prometheus
      app.kubernetes.io/component: database
      app.kubernetes.io/instance: mysql-1
      app.kubernetes.io/name: mysql
      app.kubernetes.io/part-of: prometheus-operated
      app.kubernetes.io/managed-by: Helm
  endpoints:
  - port: metrics
    interval: 30s