apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: postgres-monitor
  # Change this to the namespace the Prometheus instance is running in
  namespace: default
  labels:
    app: postgres
    release: prometheus
spec:
  selector:
    matchLabels:
      app: postgres 
  endpoints:
  - port: metrics
    interval: 30s


