apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- frontend-deployment.yaml
- service-frontend-lb.yaml
# - ../issuers/letsencrypt-prod.yaml
# - ../ingress/ingress_ssl.yaml

images:
- name: amitbb16/frontend-app
  newTag: 1.0.0